service: books

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x


functions:
  hello:
    handler: handler.getDefaultersList
    events:
      - http:
          path: getDefaultersList
          method: get